# [4] Numpy: 통계

### [실습 1] 중심 경향 및 산포 측도 계산


아래 배열에서 평균, 중앙값, 최빈값, 분산, 표준편차, 범위를 계산하세요.


```python
	arr = np.array([10, 20, 30, 30, 40, 50, 60])
```

In [11]:
import numpy as np
arr = np.array([10, 20, 30, 30, 40, 50, 60])
print(np.mean(arr))
print(np.median(arr))
# arr 최빈값


# 최빈값: 가장 자주 등장하는 값
# -> np.unique(ndarray, return_counts=True)
# return_counts=True 옵션: 중복을 제거하면서 같은 값이 몇 개 있는지 카운트해서 반환
# print(np.unique(scores, return_counts=True))
values, counts = np.unique(arr, return_counts=True)
max_count = np.max(counts)
# 중복 제거된 배열에서 최빈값을 가진 수만 찾기
vals = values[counts == max_count]
print("최빈값: ", vals)


print(np.var(arr))
print(np.std(arr))

34.285714285714285
30.0
scores 중복값 제거:  [10 20 30 40 50 60]
최빈값:  [30]
253.06122448979593
15.90789817951435


### [실습 2] 정규분포와 균등분포의 난수 생성


정규분포와 균등분포에서 각각 난수를 생성하여, 평균과 표준편차를 계산하세요.

1. 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
2. 0과 1 사이의 균등분포 난수 1000개 생성

In [12]:
# 1 평균 0, 표준편차 1인 정규분포 난수 1000개 생성
np.random.normal(0, 1, 1000)

# 2 0과 1 사이의 균등분포 난수 1000개 생성
np.random.randint(0, 1, 1000)

array([-7.65490690e-01,  6.91995265e-01,  5.54279857e-01,  6.52059561e-01,
        6.26490125e-01, -1.45894096e+00, -1.40647207e+00, -7.25521435e-01,
       -3.34714552e-01,  1.28008488e+00,  5.52842103e-01, -1.48219283e-02,
       -1.11925061e+00,  2.53977655e-01, -4.25337572e-01,  5.84200352e-01,
        1.29315177e+00,  3.21497221e-01, -1.17446233e+00,  3.92849300e-01,
        1.27171909e+00,  1.30297408e+00,  1.16433462e+00, -1.73698209e-01,
        1.07831451e-01,  1.49842580e+00,  9.08552665e-01, -5.88547955e-01,
       -1.31713332e+00,  3.73249013e-01, -2.24337929e-01, -4.14980289e-01,
        1.31755088e+00,  3.34413361e-01,  6.94247544e-01, -2.09030042e-01,
        8.14408780e-01, -9.25210889e-02,  2.70632394e-01, -7.73490513e-02,
        1.10660618e+00, -4.83841246e-01,  1.12121371e+00,  1.78302829e-02,
       -9.60316457e-01,  7.00777967e-01, -7.52249087e-01, -6.42194517e-01,
       -1.43604310e+00, -8.09297420e-01,  1.42549640e+00, -7.52158335e-02,
       -2.56576776e-01, -

### [실습 3] 평균 성적 구하기


아래와 같이 학생별 과목 성적 데이터가 주어졌을 때, 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.


```python
# 학생별 과목 성적 데이터
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]
```

In [21]:
# 각 학생의 전체 평균 성적(수학, 영어, 과학)을 계산한 후, 이 평균값에 대한 분산과 표준편차를 구하세요.
scores_math = [88, 92, 76, 85, 95, 92, 88, 90, 85, 88]
scores_english = [90, 85, 80, 87, 92, 89, 83, 91, 86, 88]
scores_science = [85, 88, 82, 89, 94, 86, 91, 88, 84, 87]

sum = np.array(scores_math) + np.array(scores_english) + np.array(scores_science)
print(sum)
scores_mean = (sum // 3)
print(sum)

[263 265 238 261 281 267 262 269 255 263]
[263 265 238 261 281 267 262 269 255 263]
