# [5] Numpy: 정렬

### [실습 1] 1차원 배열 정렬


다음 1차원 배열을 오름차순 및 내림차순으로 정렬하세요.


```python
arr = np.array([50, 10, 30, 40, 20])
```

In [1]:
import numpy as np

In [24]:
arr = np.array([50, 10, 30, 40, 20])

indices = np.argsort(arr)
print("오름차순 정렬: ", arr[indices])

indices_ = np.argsort(-arr)
print("내림차순 정렬: ", arr[indices_])

print('')
print(indices)

오름차순 정렬:  [10 20 30 40 50]
내림차순 정렬:  [50 40 30 20 10]

[1 4 2 3 0]


### [실습 2] 2차원 배열 축 기준 정렬


다음 2차원 배열을 행과 열을 기준으로 각각 정렬하세요.


```python
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
```

In [30]:
arr2d = np.array([[8, 3, 5],
                  [2, 9, 1]])

print("행 정렬: \n", np.sort(arr2d, axis=0))
print("열 정렬: \n", np.sort(arr2d, axis=1))


행 정렬: 
 [[2 3 1]
 [8 9 5]]
열 정렬: 
 [[3 5 8]
 [1 2 9]]


### [실습 3] 인덱스를 반환하는 정렬


다음 1차원 배열에서 정렬된 결과의 인덱스를 반환하고, 그 인덱스를 사용하여 배열을 정렬하세요.


```python
arr = np.array([15, 10, 20])
```

In [36]:
arr = np.array([15, 10, 20])

indices = np.argsort(arr)
print(indices)

print("정렬된 배열: ", arr[indices])


[1 0 2]
정렬된 배열:  [10 15 20]
