# [7] Numpy 종합 실습

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

- **데이터 (**각 지점의 월별 과일 판매량(단위: 개))


In [2]:
import numpy as np
from mpl_toolkits.axes_grid1.axes_divider import make_axes_area_auto_adjustable

# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
        # 지점 1
        [[120, 150, 200, 230, 180, 210],  # 사과 판매량
         [100, 140, 170, 190, 160, 180],  # 바나나 판매량
         [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

        # 지점 2
        [[80, 90, 110, 140, 130, 120],
         [60, 70, 90, 100, 110, 95],
         [50, 80, 100, 110, 90, 85]],

        # 지점 3
        [[130, 140, 160, 180, 170, 190],
         [110, 120, 130, 150, 140, 160],
         [100, 110, 120, 130, 120, 140]],

        # 지점 4
        [[100, 130, 150, 170, 160, 180],
         [90, 100, 110, 120, 130, 125],
         [80, 110, 140, 130, 120, 110]],

        # 지점 5
        [[90, 110, 130, 140, 120, 130],
         [70, 85, 100, 110, 105, 95],
         [60, 90, 110, 100, 90, 95]]
])

fruits = np.array(["사과", "바나나", "오렌지"])
branches = np.array(["지점1", "지점2", "지점3", "지점4", "지점5"])
months = np.array(["1월", "2월", "3월", "4월", "5월", "6월"])

In [3]:
# 1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
branch_avgs = np.mean(sales_data, axis=2) # 각 지점 과일별 판매 평균  #  (5, 3, 6)
print(branch_avgs)
#      사과          바나나        오렌지
# [[181.66666667 156.66666667 131.66666667]     1 지점
#  [111.66666667  87.5         85.83333333]     2 지점
#  [161.66666667 135.         120.        ]     3 지점
#  [148.33333333 112.5        115.        ]     4 지점
#  [120.          94.16666667  90.83333333]]    5 지점

print("각 지점 과일 6개월 판매 평균")
for b_index, b_name in enumerate(branches):
    print(b_name)
    for f_index, f_name in enumerate(fruits):
        print(f"{f_name} : {branch_avgs[b_index, f_index]:.0f}") #.2f = 소수점 아래 둘째 자리까지





[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
각 지점 과일 6개월 판매 평균
지점1
사과 : 182
바나나 : 157
오렌지 : 132
지점2
사과 : 112
바나나 : 88
오렌지 : 86
지점3
사과 : 162
바나나 : 135
오렌지 : 120
지점4
사과 : 148
바나나 : 112
오렌지 : 115
지점5
사과 : 120
바나나 : 94
오렌지 : 91


In [ ]:
# 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
# print(sales_data[:, 0, :])
print(np.sum(sales_data[:, 0, :], axis=0))  # 월별 사과 합
monthly_sum_apple = np.sum(sales_data[:, 0, :], axis=0)

# print(sales_data[:, 1, :])
print(np.sum(sales_data[:, 1, :], axis=0))  # 월별 바나나 합
monthly_sum_banana = np.sum(sales_data[:, 1, :], axis=0)

# print(sales_data[:, 2, :])
print(np.sum(sales_data[:, 2, :], axis=0))  # 월별 오렌지 합
monthly_sum_orange = np.sum(sales_data[:, 2, :], axis=0)

montly = [monthly_sum_apple, monthly_sum_banana, monthly_sum_orange]
print(montly)

monthly = np.array(montly)
monthly_max_sales = np.max(montly, axis=0)
print("monthly_max_sales: ", monthly_max_sales)
monthly_max_fruit = np.argmax(montly, axis=0)   # [0 0 0 0 0]
print("monthly_max_fruit: ", monthly_max_fruit)
print(fruits[monthly_max_fruit])    # 사과 사과 사과 사과 사과

for i in range(len(monthly_max_fruit)):
    print(f'{i+1}월 최다 판매 과일: {fruits[monthly_max_fruit][i]}')


# print(sales_data[:,0])
# print("사과 판매량(최대): ", np.max(sales_data[:, 0]))
# apple_sales = np.max(sales_data[:, 0])
#
# print("바나나 판매량(최대): ", np.max(sales_data[:, 1]))
# banana_sales = np.max(sales_data[:, 1])
#
# print("오렌지 판매량(최대): ", np.max(sales_data[:, 2]))
# orange_sales = np.max(sales_data[:, 2])
#
# monthly_max_sales = [apple_sales, banana_sales, orange_sales]
# print(fruits[np.argmax(monthly_max_sales)]) # 사과
# monthly_max_fruit = fruits[np.argmax(monthly_max_sales)]    # 사과
#
#
# print(np.max(sales_data[:, 0, :], axis=0))  # 월별 가장 많이 판매된 과일 수
# print(np.argmax(sales_data[:, 0, :], axis=0))  # 월별 가장 많이 판매된 과일 수




In [ ]:
# 3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.

np.sum(sales_data[0, :], axis=1)    # 지점 1 판매량: [사과, 바나나, 오렌지] [1090 940 790]
np.sum(sales_data[:, 0, :], axis=1) # [지점1 지점2 지점3 지점4 지점5] 사과 판매량
print(np.sum(np.sum(sales_data[:, 0, :], axis=1))) # 사과 총 판매량 4340
apple = np.sum(np.sum(sales_data[:, 0, :], axis=1))

print(np.sum(np.sum(sales_data[:, 1, :], axis=1))) # 바나나 총 판매량 3515
banana = np.sum(np.sum(sales_data[:, 1, :], axis=1))

print(np.sum(np.sum(sales_data[:, 2, :], axis=1))) # 오렌지 총 판매량 3260
orange = np.sum(np.sum(sales_data[:, 2, :], axis=1))

max_sales = [apple, banana, orange] # [4340 3515 3260]

print("최대 판매량: ", np.max(np.array))
print(np.argmax(max_sales))

print(fruits[np.argmax(max_sales)]) # 사과
max_sales_fruit = fruits[np.argmax(max_sales)]
# fruits = np.array(["사과", "바나나", "오렌지"])
# 이게 무슨 과일인지는 모르겠음미다.
# 과일명 출력 어케해요

print(f'가장 많이 판매된 과일: {max_sales_fruit}, {apple} 개')



In [7]:
# 4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
# - **데이터 (**각 지점의 월별 과일 판매량(단위: 개))
sales_data[sales_data > 150]

array([200, 230, 180, 210, 170, 190, 160, 180, 160, 160, 180, 170, 190,
       160, 170, 160, 180])