In [1]:
import numpy as np

In [4]:
# [1] Numpy: ndarray 기초
# 1 크기가 4x3인 모든 값이 0인 배열
arr = np.zeros((4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 2 크기가 3x3인 모든 값이 1인 배열
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# 3 0에서 20까지 5씩 증가하는 값으로 구성된 배열
arr = np.arange(0,21,5)
print(arr)


[ 0  5 10 15 20]


In [12]:
# 4 0과 1 사이의 4개의 등간격 값을 가진 배열
arr = np.linspace(0,1,4)
print(arr)

[0.         0.33333333 0.66666667 1.        ]


In [20]:
# Numpy: ndarray 인덱싱 및 슬라이싱
# [실습 1]
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print('')
# 1. 배열 arr에서 1번째 열만 추출
print(arr[:, 1])

# 2. 2번째 행, 3번째 열의 값을 출력
print(arr[1, 2])

# 3. 첫 번째 행부터 두 번째 행까지 선택하고 0번째와 1번째 열만 추출
print(arr[0:2, 0:2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]

[20 50 80]
60
[[10 20]
 [40 50]]


In [22]:
# [실습 2]
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# 1. 팬시 인덱싱을 사용하여 배열의 0번째, 2번째, 4번째 요소를 출력
print(arr[0], arr[2], arr[4])
# 2. 배열의 값 중 50보다 큰 값만 추출
print(arr[arr > 50])

10 30 50
[60 70]


In [34]:
# [실습 3]
# 어느 마트에서 판매되는 제품들의 월별 매출량이 아래와 같이 주어졌습니다. 각각의 행은 제품을 나타내고, 열은 각 월의 판매량을 나타냅니다.
sales = np.array([[120, 150, 100],
                  [80, 90, 110],
                  [200, 180, 220],
                  [50, 45, 70],
                  [300, 320, 310]])

# 1. 월별 판매량이 200개 이상인 제품의 판매량을 선택하라.
print(sales[sales >= 200])
print('')
# 2. 3월(세 번째 열)의 판매량이 100개 이하인 제품의 1월과 2월 판매량을 추출하라.
print(sales[sales[:, 2] <= 100, :2])
print('')
# 3. 2월(두 번째 열)의 판매량이 150개 이상인 제품들의 전체 월별 판매량을 출력하라.
# print(sales[:, 1][sales[1, :] >= 150])
print(sales[sales[:, 1] >= 150])

[200 220 300 320 310]

[[120 150]
 [ 50  45]]

[[120 150 100]
 [200 180 220]
 [300 320 310]]


In [ ]:
# # [3] Numpy: 연산
# 다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.
#
# 1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
# 2. 과일별 평균 판매량을 구하세요.
#
# - **데이터**:
#     - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
#     - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

